 const actionType = {
    TRACKER_LOGS:'TRACKER_LOGS',
    CREATE_LOGS:'CREATE_LOGS',
    SIGNUP_SUCCED:'SIGNUP_SUCCED',
    SIGNIN_SUCCED:'SIGNIN_SUCCED',
    SIGNIN_ERROR:'SIGNIN_ERROR',
    SIGNUP_ERROR:'SIGNUP_ERROR',
    DATABASE_CONNECTION_SUCCESS:'DATABASE_CONNECTION_SUCCESS',
    FETCH_DATA_SUCCESS:'FETCH_DATA_SUCCESS',










    PUBLISH_LIST_REQUEST:'PUBLISH_LIST_REQUEST',
    PUBLISH_LIST_SUCCESS:'PUBLISH_LIST_SUCCESS',
    PUBLISH_LIST_ERROR:'PUBLISH_LIST_ERROR',




    PUBLIC_PAGE_DETAIL_SUCCEESS:'PUBLIC_PAGE_DETAIL_SUCCEESS',




    
};
export default actionType;